OPENAI_API_KEY = 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
TWILIO_ACCOUNT_SID = AC5ae7504b0e369fe249587b4936ac5eda
TWILIO_AUTH_TOKEN = 45d88b4c1a7c6ee7fae95b1ccc8ea6f6
TWILIO_PHONE_NUMBER = +18445310432
